default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: files_processor_api
  username: <%= ENV['POSTGRES_USER'] || 'postgres
  password: <%= ENV['POSTGRES_PASSWORD'] || 'password' %>
  host: db
  port: 5432

test:
  <<: *default
  database: files_processor_api_test
  username: <%= ENV['POSTGRES_USER'] || 'postgres
  password: <%= ENV['POSTGRES_PASSWORD'] || 'password' %>
  host: db
  port: 5432

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
